### ISSUE TITLE
Typo in online documentation quoting this: Trailing comma

### ISSUE THREAD

**Issue by troldmand** [stripe-samples/charging-a-saved-card#2]
https://github.com/stripe-samples/charging-a-saved-card/blob/7870ddd29b29793a5ebedd2d5b56f0e0ab1a018d/server/node/server.js#L54-L61

The online documentation using this as an example [here](https://stripe.com/docs/payments/save-and-reuse), has a trailing comma: 

```
    const paymentIntent = await stripe.paymentIntents.create({
      amount: 1099,
      currency: 'dkk',
      customer: '{{CUSTOMER_ID}}',
      payment_method: '{{PAYMENT_METHOD_ID}}',
      off_session: true,
      confirm: true,
    });
```

Proof: 
<img width="760" alt="Screen Shot 2019-11-25 at 5 18 45 PM" src="https://user-images.githubusercontent.com/9819978/69557920-a925c000-0fa7-11ea-9a0c-cc7c334ae6ab.png">

**Comment by thorsten-stripe** [comment]
Closing as this doesn't affect the functionality of the sample.
